baseURL = 'https://littleloaf.co/'
languageCode = 'en-us'
title = 'Little Loaf Company'
theme = 'leaven'

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'Gallery'
pageRef = '/gallery'
weight = 20

[[menus.main]]
name = 'Resources'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 40
